// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT
package test

import (
	encoding "encoding"

	uuid "github.com/google/uuid"
)

type ID struct {
	Value uuid.UUID `json:"value"`
}

var (
	_ encoding.TextMarshaler   = ID{}
	_ encoding.TextUnmarshaler = (*ID)(nil)
)
